# Making Generators

In [1]:
import tensorflow as tf

In [2]:
image_data_gen = tf.keras.preprocessing.image.ImageDataGenerator(
    rotation_range = 180,
    height_shift_range = 0.25,
    width_shift_range = 0.25,
    horizontal_flip = True,
    vertical_flip = True,
    shear_range = 60,
    zoom_range = 0.8,
    brightness_range = [0, 2],
    rescale = 1/255,
    channel_shift_range = 100
)

In [3]:
test_data_gen = tf.keras.preprocessing.image.ImageDataGenerator(
    rotation_range = 90,
    horizontal_flip = True,
    vertical_flip = True,
    rescale = 1/255
)

In [4]:
Train_path = 'Data/train'
Valid_path = 'Data/validation'
Test_path = 'Data/test'
IMG_SIZE = 32
BATCH_SIZE = 32

In [5]:
train_generator = image_data_gen.flow_from_directory(
    Train_path,
    target_size=(IMG_SIZE, IMG_SIZE),
    color_mode = 'grayscale',
    class_mode = 'binary',
    batch_size = BATCH_SIZE,
    shuffle=True,
)

Found 13979 images belonging to 2 classes.


In [6]:
valid_generator = image_data_gen.flow_from_directory(
    Valid_path,
    target_size=(IMG_SIZE, IMG_SIZE),
    color_mode='grayscale',
    class_mode='binary',
    batch_size=BATCH_SIZE,
    shuffle=True
)

Found 6000 images belonging to 2 classes.


In [7]:
test_generator = test_data_gen.flow_from_directory(
    Test_path,
    target_size=(IMG_SIZE, IMG_SIZE),
    color_mode='grayscale',
    class_mode='binary',
    batch_size=1,
    shuffle=False
)

Found 4980 images belonging to 2 classes.


# Building Model

In [14]:
model = tf.keras.models.Sequential()

In [15]:
model.add(tf.keras.layers.Conv2D(6, (5,5), activation='tanh', input_shape=(32, 32, 1)))
model.add(tf.keras.layers.AveragePooling2D(pool_size=(2,2), strides=(2,2)))
model.add(tf.keras.layers.Conv2D(16, (5,5), activation='tanh', input_shape=(32, 32, 1)))
model.add(tf.keras.layers.AveragePooling2D(pool_size=(2,2), strides=(2,2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(120, activation='tanh'))
model.add(tf.keras.layers.Dense(84, activation='tanh'))
model.add(tf.keras.layers.Dense(2, activation='softmax'))

In [16]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 98, 98, 64)        640       
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 49, 49, 64)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 47, 47, 32)        18464     
                                                                 
 dropout_2 (Dropout)         (None, 47, 47, 32)        0         
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 23, 23, 32)       0         
 2D)                                                             
                                                                 
 conv2d_6 (Conv2D)           (None, 21, 21, 16)       

In [17]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [18]:
old_weights = model.get_weights()[0]

In [19]:
model.fit_generator(train_generator,
                    epochs = 20,
                    validation_data = valid_generator,
                    validation_steps=20)

/tmp/ipykernel_1035/3779622016.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  model.fit_generator(train_generator,


Epoch 1/20
437/437 [==============================] - 81s 183ms/step - loss: 0.6933 - accuracy: 0.5032 - val_loss: 0.6932 - val_accuracy: 0.4969
Epoch 2/20
437/437 [==============================] - ETA: 0s - loss: 0.6933 - accuracy: 0.5066

/home/toshan/miniconda3/envs/tf/lib/python3.9/site-packages/PIL/TiffImagePlugin.py:866: UserWarning: Truncated File Read
  warnings.warn(str(msg))


437/437 [==============================] - 76s 174ms/step - loss: 0.6933 - accuracy: 0.5066 - val_loss: 0.6934 - val_accuracy: 0.4766
Epoch 3/20
437/437 [==============================] - 74s 168ms/step - loss: 0.6931 - accuracy: 0.4985 - val_loss: 0.6931 - val_accuracy: 0.5188
Epoch 4/20
437/437 [==============================] - 75s 170ms/step - loss: 0.6931 - accuracy: 0.4963 - val_loss: 0.6923 - val_accuracy: 0.5063
Epoch 5/20
437/437 [==============================] - 73s 167ms/step - loss: 0.6933 - accuracy: 0.5033 - val_loss: 0.6922 - val_accuracy: 0.5469
Epoch 6/20
437/437 [==============================] - 71s 161ms/step - loss: 0.6927 - accuracy: 0.5151 - val_loss: 0.6917 - val_accuracy: 0.5312
Epoch 7/20
437/437 [==============================] - 70s 159ms/step - loss: 0.6920 - accuracy: 0.5211 - val_loss: 0.6945 - val_accuracy: 0.4938
Epoch 8/20
437/437 [==============================] - 70s 160ms/step - loss: 0.6910 - accuracy: 0.5229 - val_loss: 0.6951 - val_accuracy: 0.4

In [20]:
new_weights = model.get_weights()[0]

In [22]:
learning_rate = model.optimizer.get_config()['learning_rate']

In [23]:
learning_rate

0.001

In [24]:
old_weights

array([[[[-0.04330746,  0.04748785,  0.09021246, -0.09861416,
           0.05143781,  0.01069587,  0.0543918 ,  0.03414237,
           0.04231869, -0.06578051, -0.01375654, -0.02540157,
          -0.03033828, -0.07034153,  0.04084748,  0.08023444,
           0.02893725,  0.04529949,  0.02661295, -0.02539882,
          -0.028315  ,  0.05577986, -0.06311253,  0.08271733,
          -0.02618568, -0.05464982, -0.090852  , -0.00571594,
           0.08035128,  0.00303061,  0.05372261, -0.0934585 ,
          -0.01539434, -0.04226458,  0.07956305,  0.06433266,
          -0.08453608, -0.06149478,  0.08616945,  0.08968467,
           0.0719505 ,  0.07707281,  0.01661473, -0.07194866,
          -0.01584221,  0.0023992 , -0.09572444, -0.07916066,
          -0.09852374, -0.00264435,  0.10095768, -0.07900284,
           0.0594963 ,  0.0035268 , -0.00548192, -0.09830417,
           0.02941374, -0.03832156, -0.01414622, -0.10086416,
           0.00409494, -0.00593402,  0.06903912,  0.09030752]],

     

In [25]:
new_weights

array([[[[-7.40699098e-02, -1.32574633e-01,  2.81807408e-02,
          -1.93662241e-01, -9.99344140e-03, -4.39940169e-02,
           2.01799572e-02, -5.83213866e-02,  6.08019298e-03,
          -1.70142606e-01, -1.20563254e-01, -5.80065735e-02,
          -9.03419107e-02, -1.40377745e-01,  2.05814727e-02,
           1.87054835e-02, -5.17915785e-02, -3.33155878e-02,
          -5.76901883e-02, -1.03847429e-01, -8.75007138e-02,
           2.36151088e-03, -1.25223741e-01,  4.37451787e-02,
          -1.06806278e-01, -1.78757012e-01, -1.59656361e-01,
          -1.21546008e-01,  3.72759849e-02, -5.50594479e-02,
          -3.06465421e-02, -2.08560333e-01, -9.06680450e-02,
           2.68480908e-02, -5.55556640e-02,  9.92511399e-03,
          -7.03123435e-02, -1.75328717e-01,  1.72548935e-01,
           1.58118531e-02,  1.73391849e-02,  2.83605605e-02,
           1.19495854e-01, -1.88186705e-01, -6.34349212e-02,
          -6.92270696e-02, -1.70387849e-01, -1.32411763e-01,
          -1.51946351e-0

In [29]:
gradients = (old_weights-new_weights)/learning_rate
percentage_change = abs(100*(old_weights - new_weights)/old_weights)

In [30]:
percentage_change

array([[[[7.10326920e+01, 3.79175873e+02, 6.87618103e+01,
          9.63838120e+01, 1.19428200e+02, 5.11317902e+02,
          6.28989029e+01, 2.70818176e+02, 8.56323776e+01,
          1.58652008e+02, 7.76407043e+02, 1.28358231e+02,
          1.97781906e+02, 9.95659409e+01, 4.96138535e+01,
          7.66864624e+01, 2.78978912e+02, 1.73545166e+02,
          3.16774841e+02, 3.08867126e+02, 2.09026001e+02,
          9.57663803e+01, 9.84134216e+01, 4.71148567e+01,
          3.07880554e+02, 2.27095322e+02, 7.57323532e+01,
          2.02644080e+03, 5.36087227e+01, 1.91677600e+03,
          1.57045898e+02, 1.23158234e+02, 4.88970123e+02,
          1.63523849e+02, 1.69825974e+02, 8.45722046e+01,
          1.68256359e+01, 1.85111526e+02, 1.00243736e+02,
          8.23695068e+01, 7.59012299e+01, 6.32028999e+01,
          6.19216431e+02, 1.61556915e+02, 3.00417206e+02,
          2.98542456e+03, 7.79982758e+01, 6.72696533e+01,
          5.42230873e+01, 2.85728247e+03, 1.86934601e+02,
          1.28